server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${care.datasource.driver-class-name}
    url: jdbc:mysql://${care.datasource.host}:${care.datasource.port}/${care.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${care.datasource.username}
    password: ${care.datasource.password}

    druid:
      # 连接池配置
      initial-size: 5   # 初始化连接数
      min-idle: 5       # 最小空闲连接数
      max-active: 20    # 最大活跃连接数
      max-wait: 60000   # 获取连接等待超时时间（毫秒）

      # 检测配置
      time-between-eviction-runs-millis: 60000  # 间隔多久才进行一次检测，检测需要关闭的空闲连接（毫秒）
      min-evictable-idle-time-millis: 300000    # 一个连接在池中最小生存的时间（毫秒）
      validation-query: SELECT 1                # 用来检测连接是否有效的 SQL，要求是一个查询语句
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  data:
    redis:
      host: ${care.redis.host}
      port: ${care.redis.port}
      password: ${care.redis.password}
      database: ${care.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.carepaws.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    com:
      carepaws:
        mapper: debug
        service: info
        controller: info

care:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: itheima
    user-ttl: 7200000
    user-token-name: authentication
  alioss:
    endpoint: ${care.alioss.endpoint}
    access-key-id: ${care.alioss.access-key-id}
    access-key-secret: ${care.alioss.access-key-secret}
    bucket-name: ${care.alioss.bucket-name}
  wechat:
    appid: ${care.wechat.appid}
    secret: ${care.wechat.secret}
    mchid : ${care.wechat.mchid}
    mchSerialNo: ${care.wechat.mchSerialNo}
    privateKeyFilePath: ${care.wechat.privateKeyFilePath}
    apiV3Key: ${care.wechat.apiV3Key}
    weChatPayCertFilePath: ${care.wechat.weChatPayCertFilePath}
    notifyUrl: ${care.wechat.notifyUrl}
    refundNotifyUrl: ${care.wechat.refundNotifyUrl}
  shop:
    address: 北京市海淀区上地十街10号
  baidu:
    ak: your-ak
